version: "3.4"
services:

  rent-movie-api:
    container_name: rent-movie-api
    environment:
      ConnectionStrings_RentMovieContext: "Data Source=sql-server-database; Initial Catalog=RentMovieDb; User Id=sa; Password=1StrongPassword*"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_PATH=RentMovie
    depends_on:
      - sql-server-database
    command: "dotnet RentMovie.dll"
    ports:
      - "80:80"

  sql-server-database:
    container_name: sql-server-database
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: 1StrongPassword*
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
